### ISSUE TITLE
请问对于例子中neea.edu.cn这种干扰线同色的验证码识别有进展了么

### ISSUE THREAD

**Issue by T-Evan** [kur-archive/CAPTCHA_Reader#11]

**Comment by Kuri-su** [comment]
同色干扰线确实比较棘手,不过neea这种比较细, 那么我一开始的想法是先无视这个干扰线, 尝试一下, 牺牲一点识别率嘛.

不过做到一半的时候, neea似乎是为了防御四六级查询那段时间的流量, 感觉是临时增加了3-4种验证码干扰样式,(阴影 , 加强扭曲 , 固定的干扰网格), 所以后面就先弄青果去了.

**Comment by Kuri-su** [comment]
然后这种细线，可以考虑先腐蚀看看效果，

**Comment by T-Evan** [comment]
thks，期待这个项目的进展

**Comment by Kuri-su** [comment]
:sparkles: 感谢
