### ISSUE TITLE
你好，有个问题想请教下！

### ISSUE THREAD

**Issue by Hugh123456** [kur-archive/CAPTCHA_Reader#22]
就是我把你的这个类库整合到thinkphp5一直出错，不知道是包名错了还是怎么回事，可不可以你把你的这个类库放到composer上

**Comment by Kuri-su** [comment]
好的，这个是计划中的事情，这两天就做。

顺带可以贴一下错误信息吗，或许我可以帮你解决
如果是报找不到类的话，猜测可能是 `composer` 没有生成 `classmap`，可能需要修改 `composer.json` 文件，在`autoload` 的部分添加上相应的文件夹路径然后执行 `composer dumpautoload`

**Comment by Kuri-su** [comment]
已经在 `Packagist` 搞定了，执行指令 `composer require kurisu/captcha_reader dev-oop` 即可。晚一点会更新 readme，欢迎有什么bug再反馈 
:)
