### ISSUE TITLE
Error With Laravel

### ISSUE THREAD

**Issue by hungho001** [kur-archive/CAPTCHA_Reader#23]
$ php artisan --version
Laravel Framework 5.4.36

$ composer require kurisu/captcha_reader
Using version ^1.0 for kurisu/captcha_reader
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing kurisu/captcha_reader (1.0.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate

Fatal error: Cannot redeclare dd() (previously declared in /Applications/XAMPP/xamppfiles/htdocs/Travels/vendor/laravel/framework/src/Illuminate/Support/helpers.php:524) in /Applications/XAMPP/xamppfiles/htdocs/Travels/vendor/kurisu/captcha_reader/helpers.php on line 18

**Comment by Kuri-su** [comment]
嗯,因为这里的composer加载了这个项目自己声明的一个helpers文件,然后里面的dd函数和laravel自带的dd函数冲突了...

现在已经修复了,再尝试一下,

**Comment by hungho001** [comment]
Thx a lot

**Comment by Kuri-su** [comment]
我刚刚也试了下...好像还是不成功, 

可以考虑在报错之后, 直接去 `vendor/kurisu/CAPTCHA_Reader/helpers.php` 里直接把全部内容注释掉, 然后执行,`composer dumpautoload` , 如果一切正常,输出类似于如下且没有报错,
```
$ composer dumpautoload
Generating optimized autoload files
Package manifest generated successfully.
```
那说明引用成功,可以尝试在代码里调用
估计是packagist的CDN延迟还是啥的吧...我现在拉取下来的还是1.0.0的版本...

**Comment by hungho001** [comment]
我直接改掉helper.php ，可以run 但 local return "*****" 
online crash 
Call to undefined method CAPTCHAReader\src\App\GetImageInfo\GetImageInfo::getConfig()

**Comment by Kuri-su** [comment]
已经执行过 `composer dumpautoload` 了吗?

猜测是没有生成 `classmap` 导致无法加载到这个类

虽然在 `composer require ` 之后会自动生成 `classmap` ,但因为生成过程中报错导致未生成成功,所以这些类没有被加载到,所以会在类里面报 ` undefined method`
