### ISSUE TITLE
php版本7.0.30，框架版本ThinkPHP5.0,出现了这种问题= =

### ISSUE THREAD

**Issue by kuangxiaoye** [kur-archive/CAPTCHA_Reader#25]
代码如下：
```php
use CAPTCHAReader\src\App\IndexController;

class login
{
  private function getImgCode()
    {
        $path_parts = dirname(__FILE__);
        $img = $path_parts . '/img/tempimg.jpg';
        $starTime = microtime(true);
        $indexController = new IndexController();
        $res = $indexController->entrance($img, 'local');
        var_dump($res);
        $end_time = microtime(true);

        echo '执行时间为' . ($starTime - $end_time) . ' s' . "<br/>\n";
    }
}
```

报错信息如下：

> Argument 1 passed to CAPTCHAReader\src\App\Pretreatment\PretreatmentTianYShrink::getRepository() must be an instance of CAPTCHAReader\src\Traits\string, string given, called in /Applications/MAMP/htdocs/FrameWork/vendor/kurisu/captcha_reader/src/App/Pretreatment/PretreatmentTianYShrink.php on line 31 and defined

**Comment by kuangxiaoye** [comment]
我知道了  你这个···并不是扩展····啊= =难受

**Comment by kuangxiaoye** [comment]
如果别的项目想引进您的脚手架··要怎么做呢·= =

**Comment by Kuri-su** [comment]
ThinkPHP 里面用 composer引入就可以了鸭
```bash
   composer require kurisu/captcha_reader
```
然后像例子里那样调用应该就可以了鸭

-----
关于那个报错是不是改了什么东西，说这个方法需要一个 string 参数
不过没在Thinkphp里测试过，在Laravel里测试过是ok的，应该差不多鸭

**Comment by WangYeCoder** [comment]
我放弃tp5了  我要用laravel emmmm

**Comment by kuangxiaoye** [comment]
laravel的确可以调用

**Comment by Kuri-su** [comment]
不过确实是，这样只能比较方便的去引用已有的类，但是对于使用者自定义的类在框架（laravel）里没有办法去加载。
