### ISSUE TITLE
在哪里设置识别验证码的字符数量

### ISSUE THREAD

**Issue by ygzong** [kur-archive/CAPTCHA_Reader#27]
大佬你好,我想问一下如果验证码是五位或者大于五位的时候可以识别吗?

**Comment by Kuri-su** [comment]
抱歉，之前看完忘记回了。。

如果是其他的验证码的话需要改一下相应的类来支持多位验证码

**Comment by ygzong** [comment]
大佬,能详细说一下吗?我在代码里找了一遍没有找到

**Comment by Kuri-su** [comment]
如果使用的是默认的方案组,则修改如下行

* ZhengFangNormal
    * [/src/Repositories/Cutting/CuttingZhengFangFixedRepository.php:25-26](https://github.com/Kuri-su/CAPTCHA_Reader/blob/master/src/Repositories/Cutting/CuttingZhengFangFixedRepository.php#L25-L26)
* QinGuoNormal
    * [/src/Repositories/Cutting/CuttingQinGuoShrinkRepository.php:24-25](https://github.com/Kuri-su/CAPTCHA_Reader/blob/master/src/Repositories/Cutting/CuttingQinGuoShrinkRepository.php#L24-L25)
* TianYiNormal
    * [/src/Repositories/Cutting/CuttingTianYiShrinkRepository.php:25-26](https://github.com/Kuri-su/CAPTCHA_Reader/blob/master/src/Repositories/Cutting/CuttingTianYiShrinkRepository.php#L25-L26)
* NeeaNormal
    * [/src/Repositories/Cutting/CuttingNeeaFixedRepository.php:29-37](https://github.com/Kuri-su/CAPTCHA_Reader/blob/master/src/Repositories/Cutting/CuttingNeeaFixedRepository.php#L29-L37)

这里描述的是固定切割的位置,因为默认的方案组都使用的固定切割的方案,所以只改这里就可以了

如果是自己实现或搭配的组,需要找到 `Cutting` 步骤中使用的 `Repository` , 在一般切割的位置会写在`getXCoordinate()` 中

代码写的有点久了...大概应该是这些位置...

**Comment by ygzong** [comment]
谢谢,大佬

**Comment by ygzong** [comment]
大佬,我还有个问题想问一下
![captcha](https://user-images.githubusercontent.com/39479621/51582157-d1ffa380-1f05-11e9-8896-b0572f29977f.png)
是不是这种验证码很难识别啊?
![image](https://user-images.githubusercontent.com/39479621/51582205-0d9a6d80-1f06-11e9-9d3b-20e377a0b27d.png)

我发现二值化之后,出来的东西和原图相差很大,这是什么原因呢?

**Comment by Kuri-su** [comment]
抱歉...又是现在才想起来回复...

因为这个库是针对每种验证码使用不同的类去组合识别的,所以对于这种验证码专门的类

这种验证码可以参考Neea 的C类(好像是C类..)
![image](https://user-images.githubusercontent.com/22676438/51596356-bca16e00-1f33-11e9-8563-c78d9334f895.png)
也就是这种的实现稍微改一下应该就好了,二值化的时候设置的那些阈值可能要调一下

遇到困难可以发在这里

**Comment by ygzong** [comment]
好的,谢谢大佬
