### ISSUE TITLE
补全文档

### ISSUE THREAD

**Issue by Xavier9896** [kur-archive/CAPTCHA_Reader#28]
已经部署使用了，不过还是走了一点儿弯路，坐等文档更新。

**Comment by Kuri-su** [comment]
目前的简易文档可以参照 [wiki](https://github.com/Kuri-su/CAPTCHA_Reader/wiki)

具体详细的文档估计猴年马月才有...

同时 PR Wecoming :joy:  :joy:  :joy:

**Comment by Xavier9896** [comment]
> 目前的简易文档可以参照 [wiki](https://github.com/Kuri-su/CAPTCHA_Reader/wiki)
> 
> 具体详细的文档估计猴年马月才有...
> 
> 同时 PR Wecoming 😂 😂 😂

好的，昨天看漏了，没看到wiki，自己整了会儿才整好，现在打算自己重新训练，真的存在很多很简单的反而识别不出来的情况，感谢你造的轮子，在我的车上按着跑的挺快！👍🎉
