### ISSUE TITLE
项目拉下来，运行训练报错。

### ISSUE THREAD

**Issue by waney** [kur-archive/CAPTCHA_Reader#33]
请问这几个参数要怎么设置。
$beforeLine = [0, 17, 29, 41];
$afterLine  = [16, 28, 40, 54];

我这种验证码能搞吗？

![2248](https://user-images.githubusercontent.com/69211/131613206-5e5acaee-6761-4e4c-8bd0-35efaca7c46d.png)
![1558](https://user-images.githubusercontent.com/69211/131613212-fd395298-9a65-41e0-8f47-74f31cb48c1c.png)
![1232](https://user-images.githubusercontent.com/69211/131613213-f5a9a232-3f77-4cd2-9498-10838c601b23.png)
![3814](https://user-images.githubusercontent.com/69211/131613216-7f6142c5-61e0-4bb2-ad52-7285d9944813.png)
![3833](https://user-images.githubusercontent.com/69211/131613226-53cddd75-9ad2-46b5-a752-4e63256c6770.png)
![8916](https://user-images.githubusercontent.com/69211/131613234-c9cb7cd5-13d3-4aaf-b50e-c78583791cf8.png)

**Comment by Kuri-su** [comment]
需要提供具体报错内容,  本项目仅仅作为脚手架, 额外的验证码类型识别需要自行训练
