### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by imwmn** [kur-archive/CAPTCHA_Reader#6]
青果系统的验证码有没有啊？

**Comment by Kuri-su** [comment]
暂时没有提供 , 目前的主要精力是放在重构代码和加强性能上 , 以后会支持

引用readme.md的更新计划
## 更新计划
* 重构代码，改为面向对象风格，松耦合，方便更换各块的策略(已经基本完成,查看[OOP分支](https://github.com/Kuri-su/CAPTCHA_Reader_by_zhengfang/tree/oop))
* 将字典储存转为JSON储存，一次性读入内存，去掉数据库读取的时间(已经在OOP分支完成)
* 使用swoole多线程识别
* 以PHP拓展的方式重写核心函数，降低核心函数的时间复杂度

* 增加多个字典和策略
* 增加对青果验证码的支持
