### ISSUE TITLE
請問可以識別 微信搜索的驗證嗎

### ISSUE THREAD

**Issue by imagine10255** [kur-archive/CAPTCHA_Reader#9]
請問可以識別 微信搜索的驗證嗎

**Comment by Kuri-su** [comment]
现在还不可以，因为是单独针对正方教务系统的验证码。
不过现在正在准备Oop分支的支持多种验证码识别的方案

**Comment by Kuri-su** [comment]
如果可以的话，可以提供一下微信搜索验证码的url嘛？:P

**Comment by imagine10255** [comment]
這是微信搜索的驗證碼連結
http://weixin.sogou.com/antispider/util/seccode.php?tc=1511361503

這是微信官方的驗證碼連結
http://mp.weixin.qq.com/mp/verifycode?cert=1234153
cert=時間搓

我的爬蟲程式會先從微信搜索查微信公眾帳號, 然後再點進連結

建議可以把它做成 Laravel Composer Package 會方便很多

**Comment by Kuri-su** [comment]
恩，有这样的计划，做成composer的包来引用，

**Comment by Kuri-su** [comment]
这两个看起来有些麻烦，没有那么快更新

目前的精力主要还在重构主体程序上

**Comment by imagine10255** [comment]
支持!

**Comment by Kuri-su** [comment]
感谢 ! XD
